name: UAPS
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - scikit-learn
      - pandas
      - numpy
      - mlflow
      - pytest
      - tqdm
      - torch
